[package]
name = "arc-preprocessor"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[dependencies]
regex      = { version = "1.7.1" }
mdbook     = { version = "0.4.25" }
serde_json = { version = "1.0.91" }
anyhow     = { version = "1.0.68" }
