[package]      
name           = "arc-script"
version        = "0.1.0"
authors        = ["Klas Segeljakt <klasseg@kth.se>"]
description    = "The Arc-Script compiler."
homepage       = "https://cda-group.github.io/"
repository     = "https://www.github.com/segeljakt/arc-script"
documentation  = "https://segeljakt.github.io/arc-script/"
readme         = "README.md"
keywords       = ["compiler", "data-science"]
categories     = ["science", "database"]
license        = "MIT"
# license-file   = "" TODO
edition        = "2018"
build          = "build.rs"
publish        = false
default-run    = "arc-script"

[lib]
name           = "arc_script"
path           = "src/lib.rs"

[[bin]]
name           = "arc-script"
path           = "src/main.rs"

[[bench]]
name           = "bench"
harness        = false

[features]
default     = []
all         = ["provider", "manifest", "incremental", "lsp", "repl"]
shaper      = ["z3"]
repl        = ["linefeed"]
provider    = ["reqwest", "http", "http-serde", "tempfile", "quick-protobuf", "pb-rs", "avro-rs", "glob"]
manifest    = ["toml", "tempfile", "http", "http-serde"]
incremental = ["salsa"]
lsp         = ["tower-lsp", "tokio", "codespan-lsp", "trie-rs", "lazy_static", "async-trait"]

[dependencies]
# logos              = "0.11.0"
regex              = "1.3.9"
lalrpop-util       = "0.19.0"
ena                = "0.14.0"
codespan           = "0.9.5"
codespan-reporting = "0.9.5"
derive_more        = { version = "0.99.9", default-features = false, features = ["constructor"] }
num-traits         = "0.2.12"
arrayvec           = "0.5.1"
smartstring        = "0.2.3"
educe              = { version = "0.4.13", default-features = false, features = ["Hash", "PartialEq"] }
chrono             = "0.4.15"
lasso              = "0.3.1"
anyhow             = "1.0.32"
clap               = { git = "https://github.com/clap-rs/clap/", features = ["derive"]}
serde              = "1.0.115"
serde_derive       = "1.0.115"
serde_json         = "1.0.57"

# -- Feature: shaper
z3                 = { optional = true, version = "0.6.0" }

# -- Feature: repl
linefeed           = { optional = true, version = "0.6.0" }

# -- Feature: provider
reqwest            = { optional = true, version = "0.10.7", features = ["blocking"] }
http               = { optional = true, version = "0.2.1" }
http-serde         = { optional = true, version = "1.0.1" }
quick-protobuf     = { optional = true, version = "0.7.0" }
pb-rs              = { optional = true, version = "0.9.0" }
avro-rs            = { optional = true, version = "0.11.0" }
glob               = { optional = true, version = "0.3.0" }
zip                = { optional = true, version = "0.5.6" }

# -- Feature: manifest
toml               = { optional = true, version = "0.5.6" }
tempfile           = { optional = true, version = "3.1.0" }

# -- Feature: incremental
salsa              = { optional = true, version = "0.15.2" }

# -- Feature: lsp
tower-lsp          = { optional = true, version = "0.12.1" }
tokio              = { optional = true, version = "0.2.22", features = ["rt-core", "macros", "io-std"] }
codespan-lsp       = { optional = true, version = "0.10.0" }
trie-rs            = { optional = true, version = "0.1.1" }
lazy_static        = { optional = true, version = "1.4.0" }
async-trait        = { optional = true, version = "0.1.37" }
petgraph = "0.5.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen       = "0.2.67"

[build-dependencies]
lalrpop            = { version = "0.19.0", features = [ "lexer" ] }

[dev-dependencies]
criterion          = "0.3.3"
criterion-cpu-time = "0.1.0"
include_dir        = "0.6.0"
proptest           = "0.10.1"
honggfuzz          = "0.5.49"
goldentests        = "0.3.6"

# -- The development profile, used for `cargo build`.
[profile.dev]
opt-level        = 0
debug            = 2
debug-assertions = true
rpath            = false
lto              = false
panic            = 'unwind'
incremental      = true

# -- The release profile, used for `cargo build --release`.
[profile.release]
opt-level        = 3
debug            = 0
debug-assertions = false
rpath            = false
lto              = false
codegen-units    = 1
panic            = 'unwind'

# -- The testing profile, used for `cargo test`.
[profile.test]
opt-level        = 0
debug            = 2
debug-assertions = true
rpath            = false
lto              = false
codegen-units    = 1

# -- The benchmarking profile, used for `cargo bench`.
[profile.bench]
opt-level        = 3
debug            = 0
rpath            = false
lto              = false
debug-assertions = false
codegen-units    = 1
