[workspace]
members = [
  "core",
  "macros/spanned-derive",
  "wasm",
]

# -- The development profile, used for `cargo build`.
[profile.dev]
opt-level        = 0
debug            = 2
debug-assertions = true
rpath            = false
lto              = false
panic            = 'unwind'
incremental      = true

# -- The release profile, used for `cargo build --release`.
[profile.release]
opt-level        = 3
debug            = 0
debug-assertions = false
rpath            = false
lto              = false
codegen-units    = 1
panic            = 'unwind'

# -- The testing profile, used for `cargo test`.
[profile.test]
opt-level        = 0
debug            = 2
debug-assertions = true
rpath            = false
lto              = false
codegen-units    = 1

# -- The benchmarking profile, used for `cargo bench`.
[profile.bench]
opt-level        = 3
debug            = 0
rpath            = false
lto              = false
debug-assertions = false
codegen-units    = 1

# --- Optimize for small binaries when compiling for the web
[profile.release.package.arc-script-wasm]
opt-level = "s"
