[package]
name    = "arc-script-test-trybuild"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT"

[dependencies]
trybuild           = { version = "1.0.39" }

[dev-dependencies]
arcon       = { git = "https://github.com/cda-group/arcon" }
arc-script  = { path = "../../" }
