[package]
name = "exec-mlir-from-rust"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
description = "Demonstration of how to execute MLIR dialects from Rust."
build = "build.rs"

[dependencies]
