[package]
name        = "arc-script-test-compile"
version     = "0.0.0"
authors     = ["Klas Segeljakt <klasseg@kth.se>"]
edition     = "2018"
license     = "MIT"
description = "Tests to see if arc-scripts compile"
build       = "build.rs"

[dependencies]
# trybuild        = { version = "1.0.39" }
arc-script-core = { version = "=0.0.0", path = "../../arc-script-core" }
insta           = { version = "1.6.0", features = ["glob"] }
regex           = { version = "1.4.3" }
lazy_static     = { version = "1.4.0" }
# compiletest     = { version = "0.6.0", package = "compiletest_rs", features = ["tmp"] }
# cargo_toml      = { version = "0.8.1" }
arcon           = { git = "https://github.com/segeljakt/arcon" }
arc-script      = { version = "=0.0.0", path = "../../" }
prost           = { version = "0.7.0" }

[build-dependencies]
arc-script-build = { version = "=0.0.0", path = "../../arc-script-api/build" }
# arcon           = { git = "https://github.com/segeljakt/arcon" }
# arc-script      = { version = "=0.0.0", path = "../../" }
# prost           = { version = "0.7.0" }
