[package]
name    = "arc-script-test-trybuild"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[dependencies]
trybuild           = { version = "1.0.39" }

[dev-dependencies]
arc-script-bridge  = { path = "../arc-script-bridge" }
