[package]
name = "arc-script-arcorn-arctime"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
description = "A bridge between MLIR and Arctime."
license = "MIT"

[dependencies]
arctime                          = { version = "=0.0.0", path = "../../../../arctime" }
arc-script-arcorn-arctime-macros = { version = "=0.0.0", path = "./macros" }
