[package]
name    = "arc-script-test-integration"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT"
build   = "build.rs"

[dependencies]
arcon = { git = "https://github.com/cda-group/arcon" }
arc-script = { path = "../../" }

[build-dependencies]
arc-script = { path = "../../" }
