[book]
authors = ["Klas Segeljakt", "Frej Drejhammar"]
description = "Arc-Lang documentation."
language = "en"
multilingual = false
src = "src"
title = "Arc-Lang"

[build]
build-dir = "target"
create-missing = true

[preprocessor.arc-preprocessor]
command = "./arc-preprocessor/target/debug/arc-preprocessor"
renderer = ["html"]
after = ["links"]

[preprocessor.bib]
title = "References"
bibliography = "references.bib"

[preprocess.index]

[preprocess.links]

[output.html]
theme = "theme"
no-section-label = true
git_repository_url = "www.github.com/cda-group/arc"
git_repository_icon = "fa-github"
mathjax-support = true
curly-quotes = false

[output.html.playpen]
editable = false
copy-js = false

[output.html.search]
enable = true

[output.linkcheck]
follow-web-links = false
warning-policy = "error"

[output.html.fold]
enable = false
level = 0

[output.html.print]
enable = true
