[book]
authors = ["Klas Segeljakt", "Frej Drejhammar"]
description = "Arc-Lang documentation."
language = "en"
multilingual = false
src = "src"
title = "Arc-Lang"

[build]
build-dir = "target"
create-missing = true

[preprocessor.arc-preprocessor]
command = "./arc-preprocessor/target/debug/arc-preprocessor"
renderer = ["html"]
after = ["links"]

[preprocessor.bib]
bibliography = "bibliography.bib"
title = "Bibliography"

# Convert all chapter files named README.md into index.md
[preprocess.index]

# Expands the {{ #playground }}, {{ #include }}, and {{ #rustdoc_include }}
[preprocess.links]

[output.html]
theme = "theme"
no-section-label = true
git_repository_url = "www.github.com/cda-group/arc"
git_repository_icon = "fa-github"
mathjax-support = true
curly-quotes = false

[output.html.playpen]
editable = false
copy-js = false

[output.html.search]
enable = true

[output.linkcheck]
follow-web-links = false
warning-policy = "error"
exclude = [ "bibliography" ]

[output.html.fold]
enable = true
level = 0

[output.html.print]
enable = true
