[package]
name    = "arc-script-test-insta"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT"

[dependencies]
arc-script-core = { version = "=0.0.0", path = "../../arc-script-core" }
insta           = { version = "1.5.2", features = ["glob"] }
