[package]
name = "arc-script-include"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[features]
proc = ["arc-script-include-proc"]

[dependencies]
arc-script-include-proc = { version = "=0.0.0", path = "./proc", optional = true }
