name: arc-mlir

on:
  pull_request:
    branches: [ mlir ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Update submodule
      run: git submodule update --init --recursive

    - name: Build and test arc-frontend
      run: |
        cd arc-frontend
        sbt test assembly

    - name: Build and test arc-mlir
      run: |
        cd arc-mlir
        ./arc-mlir-build
        ninja check-arc-mlir -C $A2M_BUILD/llvm-build/
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}
