name: arc-script

on:
  pull_request:
    branches: [ mlir ]

env:
  CARGO_TERM_COLOR: always
  working-directory: ./arc-script

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: cargo-check
      run: cargo check --all-features

    - name: cargo-check-tests
      run: cargo check --all-features --tests

    - name: cargo-check-examples
      run: cargo check --all-features --examples

    - name: cargo-check-benches
      run: cargo check --all-features --benches
    
    - name: cargo-test
      run: cargo test --all-features

    - name: cargo-clippy
      run: cargo clippy --all-features

    - name: cargo-fmt
      run: cargo fmt -- --check
