name: arc-mlir

on:
  pull_request:
    branches: [ mlir ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Scala
      uses: olafurpg/setup-scala@v5

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v1

    - name: Update submodule
      run: git submodule update --init --recursive

    - name: Build and test arc-frontend
      run: |
        cd arc-frontend
        sbt test assembly

    - name: Build and test arc-mlir
      run: |
        cd arc-mlir
        ./arc-mlir-build
        ninja check-arc-mlir -C $A2M_BUILD/llvm-build/
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}
