name: arc-script

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./arc-script

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: cargo-fetch
      run: |
        cargo fetch

    - name: cargo-clean
      run: cargo clean

    - name: cargo-test
      run: cargo insta test --package=arc-script-test-compile

    - name: cargo-clippy
      run: cargo clippy

    - name: cargo-check
      run: cargo check

    - name: cargo-check-bins
      run: cargo check --bins

    - name: cargo-check-tests
      run: cargo check --tests

    - name: cargo-check-examples
      run: cargo check --examples

    - name: cargo-check-benches
      run: cargo check --benches
    
    - name: cargo-fuzz
      run: cargo fuzz run parse -- -runs=10000 -only-ascii

#    - name: cargo-fmt
#      run: cargo fmt -- -v --check

    - name: Check for dirty tree
      run: |
        ../check-for-dirty-tree
