name: github pages

on:
  push:
    branches:
      - mlir

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo dependencies
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/Cargo.lock') }}
          path: target
          restore-keys: |
            ${{ runner.os }}-wasm-

      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build arc-script-website-repl
        run: wasm-pack build
        working-directory: ./arc-script/website/repl

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Compile website
        run: |
          npm install
          npm run build
        working-directory: ./arc-script/website/repl/www

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup graphviz
        uses: kamiazya/setup-graphviz@v1

      - name: Build mdbook graphs
        run: dot -Tpng ./docs/src/*.dot -O

      - name: Build mdbook
        run: mdbook build ./docs/ --dest-dir ../arc-script/website/repl/www/dist/book

      - name: Deploy to gh-pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_PAGES }}
          publish_dir: ./arc-script/website/repl/www/dist
          force_orphan: true

