name: GitHub pages

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex latexmk texlive-bibtex-extra biber

    - name: Build Arc-Report
      run: |
        latexmk arc-report/main.tex -outdir=arc-report/target -cd -silent -xelatex -bibtex -pdf > /dev/null
        mv arc-report/target/main.pdf arc-website/src/Arc-Report.pdf

    - name: Setup mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Cache custom mdbook preprocessors
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          arc-website/**/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('arc-website/**/Cargo.lock') }}

    - name: Build grammar preprocessors
      run: cargo build --manifest-path arc-website/grammar/Cargo.toml

    - name: Build syntax preprocessors
      run: cargo build --manifest-path arc-website/syntax/Cargo.toml

    - name: Build mdbook-linkcheck preprocessor
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook-linkcheck
        version: latest
        use-tool-cache: true

    - name: Build mdbook-bib preprocessor
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook-bib
        version: latest
        use-tool-cache: true

    - name: Build Arc-Website
      run: |
        cd arc-website
        mdbook build

    - name: Deploy to gh-pages
      if: |
        success() &&
        github.event_name == 'push' &&
        github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: arc-website/target
        force_orphan: true
