name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      UPLOAD_URL: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}

  release:
    needs: ['prepare']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - linux
        # - macos
        include:
          - build: linux
            os: ubuntu-18.04
            target: x86_64-unknown-linux-musl
        # - build: macos
        #   os: macos-latest
        #   target: x86_64-apple-darwin
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-18.04'
      run: ./.github/continuous-integration.sh install-ubuntu-packages

  # - name: Install packages (macOS)
  #   if: matrix.os == 'macos-latest'
  #   run: ./.github/continuous-integration.sh install-macos-packages

    - name: Build artifacts
      run: ./build

    - name: Create package
      shell: bash
      run: |
        package="arc-${{github.ref_name}}-${{matrix.target}}"

        mkdir -p "$package"/{bin,share}

        mv README.md "$package"
        mv arc-mlir/build/llvm-build/bin/{arc,arc-lang,arc-mlir} "$package/bin"
        mv {arc-runtime,arc-lang/stdlib} "$package/share"

        tar cvf "$package.tar" "$package"

        echo "ASSET=$package.tar" >> $GITHUB_ENV

    - name: Release package
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.prepare.outputs.UPLOAD_URL }}
        asset_path: ${{ env.ASSET }}
        asset_name: ${{ env.ASSET }}
        asset_content_type: application/octet-stream

