name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
        # - build: macos
        #   os: macos-latest
        #   target: x86_64-apple-darwin
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: ./.github/continuous-integration.sh install-ubuntu-packages
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

  # - name: Install packages (macOS)
  #   if: matrix.os == 'macos-latest'
  #   run: ./.github/continuous-integration.sh install-macos-packages
  #   env:
  #     A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Build artifacts
      run: ./build
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Create package
      shell: bash
      run: |
        package="arc-${{github.ref_name}}-${{matrix.target}}"

        mkdir -p "$package"/{bin,share}

        mv README.md "$package"
        mv "$A2M_BUILD"/llvm-build/bin/{arc,arc-lang,arc-mlir} "$package/bin"
        mv {arc-runtime,arc-lang/stdlib} "$package/share"

        tar cvf "$package.tar" "$package"

        echo "ASSET=$package.tar" >> $GITHUB_ENV
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Release package
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.ASSET }}
        tag: ${{ github.ref }}
