name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    env:
      CARGO_TERM_COLOR: always
      CCACHE_CONFIGPATH: /root/actions-runner/persist/ccache-config
      PERSIST_DIR: /root/actions-runner/persist/

    steps:

      # Checkout branch which we want to test
    - name: Checkout source
      uses: actions/checkout@v2

      # Update LLVM dependency
    - name: Update submodule
      run: git submodule update --init --recursive

    - name: Execute CI
      run: ./.github/continuous-integration.sh
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Check for dirty tree
      run: ./check-for-dirty-tree
