[package]
name    = "arc-script-test-insta"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[dependencies]
arc-script-core = { path = "../arc-script-core" }
insta           = { version = "1.5.2", features = ["glob"] }
